#!/bin/bash

set -e
set -o pipefail

# This only works when using the 'default' profile
GNOME_TERM_PROFILE_ID_FILE=~/.mm-gnome-terminal-id
if [ ! -f $GNOME_TERM_PROFILE_ID_FILE ]; then
  gsettings get org.gnome.Terminal.ProfilesList default | tr -d "'" > $GNOME_TERM_PROFILE_ID_FILE
fi

DEFAULT_PROFILE_ID=$(cat $GNOME_TERM_PROFILE_ID_FILE)

usage() {
  SCRIPT_NAME=${0##*/}
  cat <<EOF

NAME

  $SCRIPT_NAME - manage GNOME Terminal font settings

SYNOPSIS

  $SCRIPT_NAME list
  $SCRIPT_NAME show
  $SCRIPT_NAME set <font_name> <font_size>   # Font name must be in quotes
  $SCRIPT_NAME size <font_size>

COMMANDS

  list  - list possible user fonts
  show  - show current font
  set   - provide font ing GVariant format (ie - 'Hack 12' with the single-quotes)
  size  - set size of current font

EOF
}

list_possible_user_fonts() {
  fc-list | grep ^$HOME \
    | sed -r 's/[^:]*: (.*):style=(.*)/\1 - \2/' \
    | sed -r 's/(.*),.*/\1/' \
    | sed -r 's/(.*),(.*) - (.*)/\1 \3/' \
    | sed -r 's/(.*) - (.*)/\1 \2/' \
    | sort
}

verify_font_name() {
  local _possible_name=$1

  if ! list_possible_user_fonts | grep -q "$_possible_name" ; then
    printf "ERROR: font name is not in list of available fonts\n\n"
    exit 1
  else
    printf "VERIFIED: font name '$_possible_name' is available\n\n"
  fi
}

set_font() {
  local _name=$1
  local _size=$2

  if [ -z "$_name" ]; then
    printf "ERROR: you must provide a <font_name>\n\n"
    usage
    exit 1
  elif [ -z "$_size" ]; then
    printf "ERROR: you must provide a <font_size>\n\n"
    usage
    exit 1
  elif [[ ! "$_size" =~ ^[0-9.]+$ ]]; then
    printf "ERROR: Font size must be a number (int or float)\n\n"
    usage
    exit 1
  fi

  verify_font_name "$_name"

  gvariant_font_str="'$_name $_size'"
  printf "Changing font to: $gvariant_font_str\n"

  dconf write \
    /org/gnome/terminal/legacy/profiles:/:$DEFAULT_PROFILE_ID/font \
    "$gvariant_font_str"
}

set_size() {
  local _size=$1
  CURRENT_FONT=$(get_current_font)
  set_font "$CURRENT_FONT" "$_size"
}

get_current_font() {
  dconf read /org/gnome/terminal/legacy/profiles:/:$DEFAULT_PROFILE_ID/font \
    | tr -d "'" \
    | sed -r 's/(.*) [0-9.]+$/\1/'
}


CMD=$1
case "$CMD" in

  "list")
    list_possible_user_fonts
    ;;

  "show")
    dconf read /org/gnome/terminal/legacy/profiles:/:$DEFAULT_PROFILE_ID/font

    printf "\nFull /org/gnome/terminal/legacy/profiles:/:<profile_id>/ data:\n\n"
    dconf dump /org/gnome/terminal/legacy/profiles:/:$DEFAULT_PROFILE_ID/
    ;;

  "set")
    set_font "$2" "$3"
    ;;

  "size")
    set_size "$2"
    ;;

  *)
    usage
    ;;
esac
